version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  api:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/api
    depends_on:
      - db
